export const CONFIG = {
  API_BASE_URL: process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8000',
  DEFAULT_TIMEOUT: 120000,
  MAX_RETRIES: 1,
  RETRY_DELAY: 2000,
  MAX_RECENT_TICKERS: 10,
  MAX_WATCHLIST_TICKERS: 20,
  MAX_TREND_ENTRIES: 20,
  MAX_CHAT_MESSAGES: 50,
  SENTIMENT_THRESHOLD: 0.2,
} as const;

export const POPULAR_TICKERS = [
  'RELIANCE', 'TCS', 'HDFCBANK', 'INFY', 'ICICIBANK',
  'HINDUNILVR', 'SBIN', 'BHARTIARTL', 'BAJFINANCE', 'WIPRO',
  'ITC', 'LT', 'AXISBANK', 'KOTAKBANK', 'HCLTECH',
  'TATAMOTORS', 'MARUTI', 'SUNPHARMA', 'TITAN', 'ASIANPAINT',
  'ULTRACEMCO', 'NESTLEIND', 'TECHM', 'POWERGRID', 'NTPC',
  'TATASTEEL', 'ONGC', 'JSWSTEEL', 'ADANIENT', 'ADANIPORTS',
  'BAJAJFINSV', 'DRREDDY', 'CIPLA', 'DIVISLAB', 'MRF',
  'COALINDIA', 'GRASIM', 'BPCL', 'EICHERMOT', 'HEROMOTOCO',
  'HINDALCO', 'VEDL', 'DLF', 'GODREJCP', 'TATAPOWER',
  'ZOMATO', 'NYKAA', 'PAYTM', 'DELHIVERY', 'PIDILITIND',
] as const;